version: "3"
services:
  app:
    container_name: "roombook-app"
    restart: always
    build:
      ./
    command: "npm start"
    ports:
      - "3000:3000"
    environment:
      GOOGLE_CLIENT_ID: "498859666359-9e9fbianh4qdsm1mpaugl9m1inc3mgn1.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "kkmIE_ru8o3jhufUatR_AuWe"
      GOOGLE_REDIRECT_URL: "http://localhost:3000/google/oauth_callback"
      DATABASE_URL: "sqlite:roombelt.sqlite"
      FORCE_HTTPS: "false"